export const lightColors = {
    colors: {
        body: '#f5f5f5',
        text: '#202020',
        textInvert: '#fff',
        label: '#707683',
        border: '#bdbdbd',
        borderLight: '#E2E2E2',
        content: '#fff',
        primary: '#518a64',
        primaryDark: '#182B1E',
        secondary: '#2b5037',
        secondaryLight: '#e4eee7',
        danger: '#e44141',
        dangerLight: '#f8d7da',
        highlightGray: '#f2f2f2',
        info: '#385f71',
        infoLight: '#ddecf3',
        woodType: '#cab29b',
        usage: '#e4eee7',
        quality: '#f4dcad',
        thicknessClass: '#c9dee7',
        calamity: '#e6baba',
        warning: '#f4d39b',
        antiFlashWhite: '#F4F8FB',
        mintGreen: '#CEF6EB',
    },
};
